--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CupidonSauce173/PigTranslate
build-by-default: true
branches:
- main
projects:
  PigTranslate:
    path: ""
    icon: PigTranslateIcon.jpg
...
