name: PigTranslate
main: CupidonSauce173\PigTranslate\PigTranslate
version: 1.0.0
api: 4.0.0
author: CupidonSauce173
description: MultiThreaded real-time translation system using LibreTranslate project